rename criteria to indicator
OpenG2P/openg2p-registry pull request #2
Opened 2022-08-16 03:39 UTC by emjay0921

2022-08-16 07:33 UTC, jeremi requested changes

2022-08-16 07:33 UTC, jeremi commented on g2p_registry_membership/models/group.py
> +    def count_individuals(self, kinds=None, indicator=None):
We should use the plural:`indicators`

2022-08-23 08:32 UTC, emjay0921 commented
Renamed Indicator to Indicators

2022-08-24 02:18 UTC, jeremi approved these changes

2022-08-24 02:18 UTC, merged