G2P-212,G2P-213, G2P-214 Registration date , birth date constrains added
OpenG2P/openg2p-registry pull request #72
Opened 2023-07-19 04:09 UTC by RamakrishnaVellala

2023-07-19 11:14 UTC, shibu-narayanan commented on g2p_registry_base/models/registrant.py
> +                error_message = "Registration date must be less than the birth date."
Registration can be on birth date.. please correct

2023-07-19 11:14 UTC, shibu-narayanan requested changes
Please can u rework on the birthdate logic

2023-07-26 12:46 UTC, shibu-narayanan approved these changes

2023-07-26 12:48 UTC, lalithkota approved these changes

2023-07-26 13:28 UTC, merged